P9_jinjaOperationalTags/urls.py
from django.contrib import admin
from django.urls import path,include
import app1, app2
from app3.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/', include('app1.urls')),
    path('app2/', include('app2.urls')),
    path('blog/', blog, name='blog'),
]

app1/urls.py
from django.urls import path
from app1.views import *

app_name='app1'
urlpatterns=[
    path('home/', home , name='home'),
]

app2/urls.py
from django.urls import path
from app2.views import *

app_name='app2'

urlpatterns=[
    path('index/', index, name='index'),
]

app3/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'home.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

app3/views.py
from django.shortcuts import render

# Create your views here.
def blog(request):
    return render(request, 'blog.html')

templates/blog.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <div style="height: 500px; width:500px; background-color:black; color:white;">
            <h1>Blog For The Day</h1>
            <h2>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus itaque quis ipsum. Similique obcaecati beatae incidunt consequuntur atque minima blanditiis qui! Dolorem minus alias quibusdam dolore quisquam impedit facere repudiandae!</h2>
            <a href="{% url 'app2:index' %}"><button>Index</button></a>
            <a href="{% url 'app1:home' %}"><button>Home</button></a>
        </div>
    </center>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HomE</title>
</head>
<body>
    <center>
        <div style="height: 500px; width:500px; background-color:black; color:white;">
            <h1>This is Home page</h1>
            <h2>for going next page
                click below button
            </h2>
            <a href="{% url 'app2:index' %}"><button>click for index</button></a>
            <a href="{% url 'blog' %}"><button>click for blog</button></a>
        </div>
    </center>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>
<body>
    <center>
        <div style="height: 500px; width:500px; background-color:black; color:white;">
            <h1>This is index page</h1>
            <h2>for going home page
                click below button
            </h2>
            <a href="{% url 'app1:home' %}"><button>click for home</button></a>
            <a href="{% url 'blog' %}"><button>click for blog</button></a>
        </div>
    </center>
</body>
</html>